name: GullsPosteriors
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - astropy
  - matplotlib
  - scipy
  - pandas
  - astroquery
  - dynesty
  - corner
  - emcee
  - pip
  - pip:
      - VBMicrolensing
